package com.gatherly.gatherly_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Represents a single row from the {@code categories} table.
 * <p>
 * This is the \"schema\" object the rest of the Spring application uses when
 * reading or writing categories through JPA. The column annotations tell
 * Hibernate how to map Java fields to PostgreSQL columns.
 */

@Entity
@Table(name = "categories")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /**
     * Primary key for the category (UUID generated by the database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Human‑readable label shown in the UI (for example \"Meetup\").
     */
    @Column(name = "name", nullable = false, length = 50, unique = true)
    private String name;

    /**
     * URL‑friendly identifier used for filtering (for example \"meetup\").
     */
    @Column(name = "slug", nullable = false, length = 50, unique = true)
    private String slug;

    /**
     * When the category record was created in the database.
     */
    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private OffsetDateTime createdAt;
}

