package com.gatherly.gatherly_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Represents a row in the {@code events} table.
 * <p>
 * This is the JPA mirror of your Postgres schema: field names are camelCase in
 * Java, while {@link Column#name()} uses snake_case to match SQL column names.
 * Rules like “virtual events need a meeting link” are enforced in the API, not
 * here—the entity only describes how data is stored and loaded.
 */
@Entity
@Table(name = "events")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Event {

    /**
     * Primary key; generated by Postgres ({@code gen_random_uuid()}) when a row is inserted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * The user who created this event (foreign key {@code organizer_id} → {@code profiles.id}).
     */
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "organizer_id", nullable = false, updatable = false)
    private Profile organizer;

    @Column(name = "title", nullable = false, length = 150)
    private String title;

    /**
     * Rich text (HTML or editor JSON) for the event description.
     */
    @Column(name = "description", nullable = false)
    private String description;

    @Column(name = "cover_image_url")
    private String coverImageUrl;

    /**
     * Whether the event is virtual, in person, or both. Immutable after creation.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "event_type", nullable = false, updatable = false, columnDefinition = "event_type_enum")
    private EventType eventType;

    /**
     * Free vs paid admission. Immutable after creation; pairs with {@link #admissionFee}.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "admission_type", nullable = false, updatable = false, columnDefinition = "admission_type_enum")
    private AdmissionType admissionType;

    /**
     * Price in CAD when {@link #admissionType} is {@link AdmissionType#paid}; must be {@code null} when free.
     */
    @Column(name = "admission_fee", precision = 10, scale = 2)
    @Positive
    private BigDecimal admissionFee;

    /**
     * Required for virtual/hybrid events; otherwise typically {@code null}.
     */
    @Column(name = "meeting_link")
    private String meetingLink;

    @Column(name = "address_line1", length = 255)
    private String addressLine1;

    @Column(name = "address_line2", length = 255)
    private String addressLine2;

    @Column(name = "city", length = 100)
    private String city;

    /**
     * Used for in-person or hybrid events; optional when the event is virtual-only.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "province", columnDefinition = "province_enum")
    private Province province;

    @Column(name = "postal_code", length = 7)
    private String postalCode;

    /**
     * IANA timezone id (for example {@code America/Toronto}) for displaying local times.
     */
    @Column(name = "timezone", nullable = false, length = 50)
    private String timezone;

    @Column(name = "start_time", nullable = false)
    private OffsetDateTime startTime;

    @Column(name = "end_time", nullable = false)
    private OffsetDateTime endTime;

    /**
     * Maximum attendees. The database prevents lowering this after creation.
     */
    @Column(name = "max_capacity", nullable = false)
    @Positive
    private Integer maxCapacity;

    /**
     * Denormalized count of confirmed RSVPs, maintained by a database trigger.
     * The application reads this value but should not try to persist changes to it.
     */
    @Column(name = "rsvp_count", nullable = false, insertable = false, updatable = false)
    private Integer rsvpCount;

    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status", nullable = false, columnDefinition = "event_status_enum")
    private EventStatus status;

    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "flag_reason", columnDefinition = "flag_reason_enum")
    private FlagReason flagReason;

    /**
     * Moderator or admin who flagged the event; {@code null} if not flagged.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "flagged_by")
    private Profile flaggedBy;

    @Column(name = "flagged_at")
    private OffsetDateTime flaggedAt;

    /**
     * Soft-delete timestamp; {@code null} while the event is visible to its organizer.
     */
    @Column(name = "deleted_at")
    private OffsetDateTime deletedAt;

    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;
}
